version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: ubuntu:22.04
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run start
          name: Start app
