version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: ubuntu:22.04
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Say hello to Mootam!"
          command: npm run build
          name: Build app
